# Configuration

title: "Zenial's Page"
description: "Work in progress."
baseurl: "/"
url: "https://zenialdev.github.io"
github_username:  "ZenialDev"
discord: "285329659023851520"
discord_username: "Zenial#0802"
author:  "ZenialDev"
footerTitle: "ZenialDev"
footerDesc: "\"I create spaghetti code.\""

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
